language: java

sudo: required
dist: trusty

jdk:
      - oraclejdk8

after_success:
      - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report -DserviceName=travis-ci -DserviceJobId=$TRAVIS_JOB_ID
