language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8

os:
  - linux
  - osx

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
