version: '{build}'

os: Windows Server 2012

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: git checkout -
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.3.1/binaries/apache-maven-3.3.1-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.3.1\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: mvn --version
  - cmd: java -version

build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test_script:
  - mvn test -B
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
